version: '3'

services:
  bardy-server-develop:
    container_name: bardy-server-develop
    links:
      - bardy-redis
    image: marconwillian/bardy-socket_notification:develop
    ports: 
      - '3104:3000'
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=production
      - HOST=bardy.mh4sh.dev
      - REDIS_URL=redis://bardy-redis