version: '3'

services:
  ecoleta-server:
    container_name: ecoleta-server
    image: marconwillian/ecoleta:latest
    ports: 
      - '3001:3000'
    command: ["node", "dist/server.js"]
    environment:
      - NODE_ENV=production
    env_file:
      - .production.env