version: '3'

services:
  ecoleta-server-develop:
    container_name: ecoleta-server-develop
    image: marconwillian/ecoleta:develop
    ports:
      - '3101:3000'
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=development
      - HOST=https://server-ecoleta.marconwillian.dev:8080
    env_file:
      - ../.production.env