version: '3'

services:
  ecoleta-server-develop:
    container_name: ecoleta-server-develop
    image: marconwillian/ecoleta:develop
    ports:
      - '3101:3000'
    command: ["node", "dist/server.js"]
    environment:
      - NODE_ENV=production
      - HOST=server-ecoleta.marconwillian.dev:8080
    env_file:
      - ../.production.env