version: '3'

services:
  ecoleta-server:
    container_name: ecoleta-server
    image: marconwillian/ecoleta:latest
    ports: 
      - '3001:3000'
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=production
      - HOST=https://server-ecoleta.marconwillian.dev
    env_file:
      - .production.env